config/routes.rb
GoodsApp::Application.routes.draw do
  
  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  resources :products
  
  root to: 'static_pages#home'
  
  get 'static_pages/home'
    
  match '/about',   to: 'static_pages#about'
  match '/contact', to: 'static_pages#contact'
  match '/signup',  to: 'users#new'
  match '/signin',  to: 'sessions#new'
  match '/signout', to: 'sessions#destroy', via: :delete
  match '/products', to: 'products#index'
  

end

app/models/product.rb
# == Schema Information
#
# Table name: products
#
#  id         :integer         not null, primary key
#  name       :string(255)
#  variety    :string(255)
#  price      :float
#  desc       :string(255)
#  image      :string(255)
#  created_at :datetime        not null
#  updated_at :datetime        not null
#

class Product < ActiveRecord::Base
  attr_accessible :desc, :image, :name, :price, :variety
  belongs_to :user
  
  validates :name, presence: true, uniqueness: { case_sensitive: false }
  validates :price, presence: true
  validates :image, presence: true, exclusion: {in: %w(Select),
    message: "must be valid"}
  validates :user_id, presence: true
  
  def price=(value)
    value = value.to_s.tr('$', '').to_f
    write_attribute(:price, value)
  end
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id         :integer         not null, primary key
#  name       :string(255)
#  email      :string(255)
#  created_at :datetime        not null
#  updated_at :datetime        not null
#

class User < ActiveRecord::Base
  attr_accessible :name, :email, :password, :password_confirmation
  has_secure_password
  has_many :products, dependent: :destroy
   
  before_save { |user| user.email = email.downcase }
  before_save :create_remember_token
  
  validates :name,  presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
  validates :password, presence: true, length: { minimum: 6 }
  validates :password_confirmation, presence: true
  
  private

    def create_remember_token
      self.remember_token = SecureRandom.urlsafe_base64
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  include SessionsHelper
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_filter :signed_in_user, only: [:index, :create, :edit, :update, :destroy, :new]
  before_filter :correct_user,   only: [:edit, :update, :destroy]
  
  def show
    @product = Product.find(params[:id])
  end
  
  def new
    @product = current_user.products.build if signed_in?
  end
  
  def create
    @product = current_user.products.build(params[:product]) if signed_in?
    if @product.save
      flash[:success] = "Product created!"
      redirect_to @product
    else
      render 'new'
    end
  end
  
  def edit
    @product = current_user.products.find_by_id(params[:id]) if signed_in?
  end
  
  def update
    @product = Product.find(params[:id]) if signed_in?
    if @product.update_attributes(params[:product])
      flash[:success] = "Product updated"
      redirect_to @product
    else
      render 'edit'
    end
  end
  
  def index
    @products = Product.paginate(page: params[:page], per_page: 12)
  end
  
  def destroy
    @product.destroy
    redirect_to user_path(current_user)
  end
  
  private
    
    def correct_user
      @product = current_user.products.find_by_id(params[:id])
      redirect_to(user_path) if @product.nil?
    end
  
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  
 def create
    user = User.find_by_email(params[:session][:email])
    if user && user.authenticate(params[:session][:password])
      sign_in user
      redirect_back_or user
    else
      flash.now[:error] = 'Invalid email/password combination'
      render 'new'
    end
  end
  
  def destroy
    sign_out
    redirect_to root_path
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :signed_in_user, only: [:index, :edit, :update, :destroy]
  before_filter :correct_user,   only: [:edit, :update]
  before_filter :admin_user,     only: :destroy
  
  def show
    @user = User.find(params[:id])
    @products = @user.products.paginate(page: params[:page], per_page: 12)
  end
  
  def new
    @user = User.new
  end
  
  def create
   @user = User.new(params[:user])
    if @user.save
      sign_in @user
      flash[:success] = "Welcome to the Sample App!"
      redirect_to @user
    else
      render 'new'
    end
  end
  
  def edit
  end
  
  def update
    if @user.update_attributes(params[:user])
      flash[:success] = "Profile updated"
      sign_in @user
      redirect_to @user
    else
      render 'edit'
    end
  end
  
  def destroy
    User.find(params[:id]).destroy
    flash[:success] = "User destroyed."
    redirect_to users_path
  end
  
  def index
    @users = User.paginate(page: params[:page])
  end
 
  private

    def correct_user
      @user = User.find(params[:id])
      redirect_to(root_path) unless current_user?(@user)
    end
    
    def admin_user
      redirect_to(root_path) unless current_user.admin?
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/products_helper.rb
module ProductsHelper
  def create_image_list()
    image_index = 1
    option_array = Array.new
    option_array.push(['Select an image', 'Select'])
    image_index += 1
    Dir.foreach("app/assets/images/goods/") { |file|
      if file.length>2 then
        option_array.push([file, file])
        image_index += 1
      end
    }
    option_array.sort!
    
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def sign_in(user)
    cookies.permanent[:remember_token] = user.remember_token
    self.current_user = user
  end
  
  def signed_in?
    !current_user.nil?
  end
  
  def current_user=(user)
    @current_user = user
  end
  
   def current_user
    @current_user ||= User.find_by_remember_token(cookies[:remember_token])
  end

  def current_user?(user)
    user == current_user
  end

  
  def signed_in_user
    unless signed_in?
      store_location
      redirect_to signin_path, notice: "Please sign in."
    end
  end
  
  def sign_out
    self.current_user = nil
    cookies.delete(:remember_token)
  end
  
  def redirect_back_or(default)
    redirect_to(session[:return_to] || default)
    session.delete(:return_to)
  end

  def store_location
    session[:return_to] = request.fullpath
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
  def first_product(user)
    user.products.first
  end
  
  
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <nav>
    <ul>
      <li><%= link_to "About",   about_path %></li>
      <li><%= link_to "Contact", contact_path %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top">
  <div class="navbar-inner">
    <div class="container">
      <%= link_to "Goods App", root_path, id: "logo" %>
      <nav>
        <ul class="nav pull-right">
          <li><%= link_to "Home",    root_path %></li>
          <% if signed_in? %>
            <li><%= link_to "Users", users_path %></li>
            <li id="fat-menu" class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                Account <b class="caret"></b>
              </a>
              <ul class="dropdown-menu">
                <li><%= link_to "My Products", current_user %></li>
                <li><%= link_to "Edit Settings", edit_user_path(current_user) %></li>
                <li class="divider"></li>
                <li>
                  <%= link_to "Sign out", signout_path, method: "delete" %>
                </li>
              </ul>
            </li>
          <% else %>
            <li><%= link_to "Sign in", signin_path %></li>
          <% end %>
        </ul>
      </nav>
    </div>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>GoodsApp | <%= yield(:title) %></title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
    <%= render 'layouts/header' %>
    <div class="container">
      <% flash.each do |key, value| %>
        <%= content_tag(:div, value, class: "alert alert-#{key}") %>
      <% end %>
      <%= yield %>
      <%= render 'layouts/footer' %>
    </div>
    <%= debug(params) if Rails.env.development? %>
    
</body>
</html>

app/views/products/_product.html.erb
<div class = "product_small">
    <div class = "product_holder">
        <%= link_to image_tag("goods/" + product.image), product %>
    </div>
    <div class = "product_info">
        <div class = "product_name"> 
            <%= link_to product.name, product %>
        </div>
        <div class = "product_type">
            <%= product.variety %>:
            <span class ="product_price">
                <%= number_to_currency(product.price, unit: "$") %>
            </span>
        </div>
        <div>
            <span>
                <% if current_user?(User.find(product.user_id)) %>
                    <%= link_to "edit", edit_product_path(product) %> | 
                    <%= link_to "delete", product, method: :delete,
                                                  data: { confirm: "You sure?" } %>
                <% end %>
            </span>
        </div>
    </div>
</div>

app/views/products/edit.html.erb
<% provide(:title, "Edit this Product") %>

<h1><%= yield(:title) %></h1>


<div>
  <%= form_for(@product) do |f| %>
  
    <%= render 'shared/error_messages', target: @product %>

    <%= f.label :name %>
    <%= f.text_field :name %>
  
    <%= f.label :variety, "Variety" %>  
    <%= f.select(:variety, [['Single Card','Single Card'],['Card Set', 'Card Set']], selected: @product.variety) %>
  
    <%= f.label :price %>
    <%= f.text_field :price %>
  
    <%= f.label :desc, "Description" %>
    <%= f.text_area :desc, :cols => "40", :rows => "10" %>
  
    <%= f.label :image, "Image" %>
    <%= f.select(:image, create_image_list, selected: @product.image) %>
  
    
    <br>
    <br>
    <%= f.submit "Save changes", class: "btn btn-large btn-primary" %>
  <% end %>
</div>

app/views/products/index.html.erb
<% provide(:title, 'All products') %>

<h1>All products</h1>

<%= will_paginate @products %>

<table class="products">
  <% @products.in_groups_of(3) do |product_row| %>
    <tr>
    <% product_row.each do |single_product| %>
      <% unless single_product.nil? %>
        <td><%= render single_product %></td>
      <% end %>  
    <% end %>
    </tr>
  <% end %>
  
</table>

<%= will_paginate @products %>

app/views/products/new.html.erb
<% provide(:title, 'New Product') %>


<h2><%= yield(:title) %></h2>

<div>
  <%= form_for(@product) do |f| %>

    <%= render 'shared/error_messages', target: @product %>
  
    <%= f.label :name %>
    <%= f.text_field :name %>
  
    <%= f.label :variety, "Variety" %>  
    <%= f.select(:variety, [['Single Item','Single Item'],['Item Set', 'Item Set']]) %>
  
    <%= f.label :price %>
    <%= f.text_field :price %>
  
    <%= f.label :desc, "Description" %>
    <%= f.text_area :desc, :cols => "40", :rows => "10" %>
  
    <%= f.label :image, "Image" %>
    <%= f.select(:image, create_image_list) %>
    
    <br>
    <br>
    <%= f.submit "Create a product", class: "btn btn-large btn-primary" %>
  <% end %>
</div>

app/views/products/show.html.erb
<% provide(:title, @product.name) %>

<div class = "product">
  <div class = "name">
    <%= @product.name %>
  </div>
  <div>
    <span class = "attribute">
      By:
    </span>
    <span>
      <%= link_to User.find_by_id(@product.user_id).name, User.find_by_id(@product.user_id) %>
    </span>  
  </div>
  <div>
    <span class="attribute">
      Price:
    </span>
    <span class="price">
      <%= number_to_currency(@product.price, :unit => "$") %></productprice>
    </span>
  </div>
  <div>
    <span class = "attribute">
      Description:
    </span>
    <span class="desc">
      <%= @product.desc %>
    </span>
  </div>
    <div>
     <% if current_user?(User.find(@product.user_id)) %>
        <%= link_to "edit", edit_product_path(@product) %> |
        <%= link_to "delete", @product, method: :delete,
                                      data: { confirm: "You sure?" } %>
      <% end %>
  </div>
  <div>
    <%= image_tag "goods/" + @product.image %>
  </div>
</div>

app/views/shared/_error_messages.html.erb
<% if target.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-error">
      The form contains <%= pluralize(target.errors.count, "error") %>.
    </div>
    <ul>
    <% target.errors.full_messages.each do |msg| %>
      <li>* <%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_new_product_feed.html.erb
<table>
  <tr>
    <% user.products.first(3).each do |single_product| %>
      <% unless single_product.nil? %>
        <td>
          <div class = "preview_box">
            <%= render partial: 'shared/product_preview', locals: {product: single_product} %>
          </div>
          <div class = "product_created_at">
            <%= single_product.created_at.strftime("%d %b %y") %>
          </div>  
        </td>
      <% end %> 
    <% end %>
    <td>
      <% if user.products.count > 3 then %>
        <%= link_to "MORE >>", user %>
      <% end %>
    </td>
  </tr>
</table>

app/views/shared/_product_preview.html.erb
    
<div class = "preview_image">
    <%= link_to image_tag("goods/" + product.image), product %>
    
</div>

app/views/shared/_user_profile.html.erb
<table>
  <tr>
    <td style="padding: 20px">
      <h3>
        <%= current_user.name %>
      </h3>
      <div>
        <%= link_to "view my products", current_user %>
      </div>
      <div>
        <%= pluralize(current_user.products.count, "product") %>
      </div>  
    </td>
    <td>
      <%= render partial: 'shared/new_product_feed', locals: {user: current_user} %>  
    </td>
  </tr>
  <tr>
    <td>
      <%= link_to "Create a Product", 'products/new', class: "btn btn-large btn-primary" %>
    </td>
  </tr>
</table>

app/views/static_pages/_home_signed_out.html.erb
<div class="center hero-unit">
    <h1>Welcome to the Goods App</h1>
    
    <h2>Add and edit products with ease and delight!</h2>
    
    <div><%= link_to "Sign In", 'signin', class: "btn btn-large btn-primary" %></div>
    <br>
    <div>Not a member? <%= link_to "Sign up now!", 'signup' %></div>
    
</div>

app/views/static_pages/about.html.erb
<% provide(:title, 'About') %>

<h1>About</h1>

<p>Goods App is a bare-bones application for users to add, edit, and delete products, as well as browse other users' goods. The Product model includes a name, product type (single item or item set), price, description, and image. Currently available images are pre-uploaded as this app is for demonstration purposes only.</p>

<p>This app was developed using Ruby on Rails and all the associated code is available on <a href="https://www.github.com/munrosarah/goods_app">GitHub</a>. Error testing is conducted with RSpec.</p>

<p>It was based on the <a href="ruby.railstutorial.org">rails tutorial</a> micropost app, but was written from scratch by <a href="http://ellipsisetc.com/resume.html">Sarah Munro</a>.</p>

app/views/static_pages/contact.html.erb
<% provide(:title, 'Contact') %>

<h1>Contact</h1>

<p>All the associated code for this application is available on <a href="https://www.github.com/munrosarah/goods_app">GitHub</a>.</p>

<p>You can contact Sarah Munro at munro.sarah@gmail.com</p>

app/views/static_pages/home.html.erb
<% provide(:title, 'Home') %>

<% if signed_in? %>
  <%= render 'shared/user_profile' %>
<% else %>
  <%= render 'home_signed_out' %>
<% end %>

app/views/users/_user.html.erb
<li>
  <table>
    <tr>
      <td style="min-width: 150px">
        <%= link_to user.name, user %>
        <% if current_user.admin? && !current_user?(user) %>
          | <%= link_to "delete", user, method: :delete,
                                        data: { confirm: "You sure?" } %>
        <% end %>
        <div>
          <%= pluralize(user.products.count, "product") %>
        </div>
      </td>
      <td>
        <% if user.products.any? %>
         <%= render partial: 'shared/new_product_feed', locals: {user: user} %>
        <% end %>
      </td>
    </tr>
  </table>
</li>

app/views/users/edit.html.erb
<% provide(:title, "Edit user") %> 
<h1>Update your profile</h1>

<div class="row">
  <div class="span6 offset3">
    <%= form_for(@user) do |f| %>
      <%= render 'shared/error_messages', target: @user %>

      <%= f.label :name %>
      <%= f.text_field :name %>

      <%= f.label :email %>
      <%= f.text_field :email %>

      <%= f.label :password %>
      <%= f.password_field :password %>

      <%= f.label :password_confirmation, "Confirm Password" %>
      <%= f.password_field :password_confirmation %>

      <%= f.submit "Save changes", class: "btn btn-large btn-primary" %>
    <% end %>

  </div>
</div>

app/views/users/index.html.erb
<% provide(:title, 'All users') %>
<h1>All users</h1>

<%= will_paginate %>

<ul class="users">
  <%= render @users %>
</ul>

<%= will_paginate %>

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>
<h1>Sign up</h1>

<div class="row">
  <div class="span6 offset3">
    <%= form_for(@user) do |f| %>
      <%= render 'shared/error_messages', target: @user %>

      <%= f.label :name %>
      <%= f.text_field :name %>

      <%= f.label :email %>
      <%= f.text_field :email %>

      <%= f.label :password %>
      <%= f.password_field :password %>

      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation %>

      <%= f.submit "Create my account", class: "btn btn-large btn-primary" %>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>
<div class="row">
<h1><%= @user.name %></h1>

  <aside>
    
  </aside>
  <div class="span8">
    <table class="products">
      <% if @user.products.any? %>
        <h3>Products (<%= @user.products.count %>)</h3>
        <%= will_paginate @products %>
        
          <% @products.in_groups_of(3) do |product_row| %>
            <tr>
            <% product_row.each do |single_product| %>
              <% unless single_product.nil? %>
                <td><%= render single_product %></td>
              <% end %>  
            <% end %>
            </tr>
          <% end %>      
        <%= will_paginate @products %>
      <% end %>
        <tr>
          <td>
            <% if current_user?(@user) then %>
              <%= link_to "Create a Product", '../products/new', class: "btn btn-large btn-primary" %>
            <% end %>
          </td>
        </tr>
    </table>
  </div>


</div>